export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';

export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH';

export const QUIZ_CONTINUE = 'QUIZ_CONTINUE';
export const QUIZ_COMPLETE_SUCCESS = 'QUIZ_CONTINUE_SUCCESS';
export const QUIZ_COMPLETE_FAILED = 'QUIZ_CONTINUE_FAILED';
export const QUIZ_QUIT = 'QUIZ_QUIT';
export const QUIZ_COMPLETE = 'QUIZ_COMPLETE';

export const COUNTER_COMPLETE = 'COUNTER_COMPLETE';