export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const PASSWORD_RESET_LINK_SENT = 'PASSWORD_RESET_LINK_SENT';
export const PASSWORD_RESET_LINK_SENT_SUCCESS = 'PASSWORD_RESET_LINK_SENT_SUCCESS';
export const PASSWORD_RESET_LINK_SENT_FAILED = 'PASSWORD_RESET_LINK_SENT_FAILED';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const CHANGE_PASSWORD_RESET_STATES = 'CHANGE_PASSWORD_RESET_STATES';


export const QUIZ_CONTINUE = 'QUIZ_CONTINUE';
export const QUIZ_COMPLETE_SUCCESS = 'QUIZ_COMPLETE_SUCCESS';
export const QUIZ_COMPLETE_FAILED = 'QUIZ_COMPLETE_FAILED';
export const QUIZ_QUIT = 'QUIZ_QUIT';
export const QUIZ_COMPLETE = 'QUIZ_COMPLETE';
export const COUNTER_COMPLETE = 'COUNTER_COMPLETE';
export const SET_NO_QF_QUESTIONS = 'SET_NO_QF_QUESTIONS';
export const RESET_ALL_QUIZ_STATES = 'RESET_ALL_QUIZ_STATES';


export const CREATE_QUIZ = 'CREATE_QUIZ';
export const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';
export const CREATE_QUIZ_FAILED = 'CREATE_QUIZ_FAILED';


export const TIMER_RUNNING = 'TIMER_RUNNING';
export const TIMER_STOPPED = 'TIMER_STOPPED';


export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';


export const SHOW_CONFIRM = 'SHOW_CONFIRM';
export const HIDE_CONFRIM = 'HIDE_CONFIRM';
export const OK_CLICKED = 'OK_CLICKED';
export const CANCEL_CLICKED = 'CANCEL_CLICKED';


export const NEW_USER = 'NEW_USER';